/*
 * SensorConfigFrame.java
 *
 * Created on 28. August 2009, 11:23
 */

package bluetoothgateway.gui;

import bluetoothgateway.FrameDetector;
import bluetoothgateway.Main;
import bluetoothgateway.bluetooth.BTConnection;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author  Clemens Lombriser <lombriser@ife.ee.ethz.ch>
 */
public class SensorConfigFrame extends java.awt.Frame implements Observer {

   private BTConnection m_btc;
   
    /** Creates new form SensorConfigFrame */
    public SensorConfigFrame(String btAddress, String sensorname, String [] formatStrings) {
        initComponents();
        
        m_txtBTAddress.setText(btAddress);
        m_txtSensorName.setText(sensorname);

        for (int i=0; i<formatStrings.length; i++) {
            m_choiceEncoding.add(formatStrings[i]);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        m_txtSensorName = new java.awt.TextField();
        label2 = new java.awt.Label();
        m_txtBTAddress = new java.awt.TextField();
        label3 = new java.awt.Label();
        m_choiceEncoding = new java.awt.Choice();
        label4 = new java.awt.Label();
        m_txtDefineFormat = new java.awt.TextField();
        label5 = new java.awt.Label();
        m_btnAutoDetect = new java.awt.Button();
        m_btnConnect = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setText("Sensor Name");

        m_txtSensorName.setText("textField1");

        label2.setText("BT Address");

        m_txtBTAddress.setText("textField1");

        label3.setText("Encoding");

        m_choiceEncoding.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceEncodingItemStateChanged(evt);
            }
        });

        label4.setText("Select known");

        label5.setText("Define");

        m_btnAutoDetect.setLabel("AutoDetect");
        m_btnAutoDetect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnAutoDetectActionPerformed(evt);
            }
        });

        m_btnConnect.setLabel("Connect");
        m_btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnConnectActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(m_txtSensorName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .add(m_txtBTAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(label4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(m_choiceEncoding, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .add(m_btnAutoDetect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .add(m_txtDefineFormat, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                    .add(m_btnConnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(m_txtSensorName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(m_txtBTAddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(38, 38, 38)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(label3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(m_btnAutoDetect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(m_choiceEncoding, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(m_txtDefineFormat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(m_btnConnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

private void choiceEncodingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceEncodingItemStateChanged

   // copy the format text to the text definition
   m_txtDefineFormat.setText( m_choiceEncoding.getSelectedItem() );
   
}//GEN-LAST:event_choiceEncodingItemStateChanged

private void m_btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnConnectActionPerformed

   Main.addBTConnection(m_txtBTAddress.getText(),m_txtSensorName.getText(),m_txtDefineFormat.getText());
   setVisible(false);

}//GEN-LAST:event_m_btnConnectActionPerformed

private void m_btnAutoDetectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnAutoDetectActionPerformed

   String[] knownFormats = new String[m_choiceEncoding.getItemCount()];
   for(int i=0;i<knownFormats.length;i++) {
      knownFormats[i] = m_choiceEncoding.getItem(i);
   }
   
   FrameDetector fd = new FrameDetector(knownFormats);
   fd.addObserver(this);
   m_btc = new BTConnection(m_txtBTAddress.getText(),fd );
   
   new Thread(m_btc).start();   
   
   m_btnAutoDetect.setEnabled(false);
}//GEN-LAST:event_m_btnAutoDetectActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SensorConfigFrame().setVisible(true);
//            }
//        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Button m_btnAutoDetect;
    private java.awt.Button m_btnConnect;
    private java.awt.Choice m_choiceEncoding;
    private java.awt.TextField m_txtBTAddress;
    private java.awt.TextField m_txtDefineFormat;
    private java.awt.TextField m_txtSensorName;
    // End of variables declaration//GEN-END:variables

   public void update(Observable o, Object arg) {
      if ( o instanceof FrameDetector ) {
         m_txtDefineFormat.setText((String)arg);
         
         m_choiceEncoding.select((String)arg);
         
         m_btc.stop();
         m_btc = null;
         m_btnAutoDetect.setEnabled(true);
      }
   }

}
