/*
    This file is part of Titan.

    Titan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as 
    published by the Free Software Foundation, either version 3 of 
    the License, or (at your option) any later version.

    Titan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Titan. If not, see <http://www.gnu.org/licenses/>.
*/

package titan.mobile;

/*
 * BTSearch.java
 * Panel for Buetooth Device Discovery
 * Created on 28. Juli 2008, 15:23
 */



/**
 * 
 * @author Mirco Rossi <mrossi@ife.ee.ethz.ch>
 */
public class BTSearchDevicesPanel extends java.awt.Panel {

    private boolean m_discoveryStarted;
    public int m_selection;

    
    /** Creates new form BTSearch */
    public BTSearchDevicesPanel() {
        initComponents();
        m_discoveryStarted=false;
        
    }
    
  /*  public void setText(String s1){
        StatusLabel.setText(s1);   

    }*/
    
    public void discoveryStoped(){
        m_discoveryStarted=false;
        FindCommand.setEnabled(true);
    }
    
private void startDeviceDiscovery() {
                m_discoveryStarted=true;
                FindCommand.setEnabled(false);
		System.out.println("Searching Devices...");
		BTList.removeAll();
		TitanMobile.startDeviceDiscovery();
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        BTList = new java.awt.List();
        FindCommand = new java.awt.Button();
        label2 = new java.awt.Label();
        QuickLinkCommand = new java.awt.Button();
        noConnectionButton = new java.awt.Button();

        label1.setText("Welcome to Titan!");

        BTList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BTListItemStateChanged(evt);
            }
        });
        BTList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTListActionPerformed(evt);
            }
        });

        FindCommand.setLabel("Find");
        FindCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindCommandActionPerformed(evt);
            }
        });

        label2.setText("Select a Bluetooth Device:");

        QuickLinkCommand.setLabel("QuickLink");
        QuickLinkCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickLinkCommandActionPerformed(evt);
            }
        });

        noConnectionButton.setLabel("don't connect");
        noConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noConnectionButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(BTList, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(label2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(noConnectionButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(QuickLinkCommand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(FindCommand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(label1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(label2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BTList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(FindCommand, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(QuickLinkCommand, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(noConnectionButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void FindCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindCommandActionPerformed
    TitanMobile.singleton.getGUI().enableNext(false);
    startDeviceDiscovery();
}//GEN-LAST:event_FindCommandActionPerformed

private void BTListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTListActionPerformed

}//GEN-LAST:event_BTListActionPerformed

private void BTListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BTListItemStateChanged
 if(BTList.getSelectedIndex()>-1){   
     //TitanMobile.setBTChoice(BTList.getSelectedIndex());
     m_selection=BTList.getSelectedIndex();
     TitanMobile.singleton.getGUI().enableNext(true);
 } else{
     TitanMobile.singleton.getGUI().enableNext(false);
 }
}//GEN-LAST:event_BTListItemStateChanged

private void QuickLinkCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickLinkCommandActionPerformed
 
 //Notebook ZAINA: btspp://0014A4D8F3EB:1;authenticate=true;encrypt=true;master=false
 //Gateway HW: btspp://0800172D42D2:1;authenticate=true;encrypt=true;master=false";
 //USB BT ANYCOM: btspp://000A3A840CAC:2;authenticate=true;encrypt=true;master=false
 
    String url="btspp://0014A4D8F3EB:1;authenticate=true;encrypt=true;master=false"; 
 

 
 TitanMobile.singleton.getGUI().QuickLink(url);
 
}//GEN-LAST:event_QuickLinkCommandActionPerformed

private void noConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noConnectionButtonActionPerformed
    TitanMobile.singleton.getGUI().TitanCommandWithoutConnection();
}//GEN-LAST:event_noConnectionButtonActionPerformed
public void appendBT(String s1){
    BTList.add(s1);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List BTList;
    private java.awt.Button FindCommand;
    private java.awt.Button QuickLinkCommand;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Button noConnectionButton;
    // End of variables declaration//GEN-END:variables

}
