/*****************************************************************************
 * Semester Thesis WSPack 6 2006
 * ETH Zürich, Inst. for Electronics
 *
 * Autor:               Felix Arnold (farnold@ee.ethz.ch)
 * Target:              MSP430F1611 Processor
 * Build Environment:   IAR Embedded Workbench V3.3A/W32
 * File:                c45.c
 *
 * C45 Decision Tree 
 * (Tree and Java-Code generated by Weka, parsed and transformed to 
 * C-Code by tocpp.pl
 *****************************************************************************/







#include "c45.h"

//konferenzraum 4 pers

uint16_t N15ba1ef22(uint16_t i[]) {
    uint16_t p ;
    if (i[5] == NULL) {
      p = 4;
    } else if (((uint16_t) i[5]) <= 3050) {
      p = 4;
    } else if (((uint16_t) i[5]) > 3050) {
      p = 6;
    } 
    return p;
  }

uint16_t N4c8b8421(uint16_t i[]) {
    uint16_t p ;
    if (i[3] == NULL) {
      p = 6;
    } else if (((uint16_t) i[3]) <= 25) {
      p = 6;
    } else if (((uint16_t) i[3]) > 25) {
      p = 4;
    } 
    return p;
  }

uint16_t Nc386d20(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 4;
    } else if (((uint16_t) i[4]) <= 4343) {
    p = N4c8b8421(i);
    } else if (((uint16_t) i[4]) > 4343) {
    p = N15ba1ef22(i);
    } 
    return p;
  }

uint16_t N19daa2019(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 0;
    } else if (((uint16_t) i[0]) <= 2314) {
      p = 0;
    } else if (((uint16_t) i[0]) > 2314) {
      p = 1;
    } 
    return p;
  }

uint16_t Nbe834a18(uint16_t i[]) {
    uint16_t p ;
    if (i[7] == NULL) {
      p = 0;
    } else if (((uint16_t) i[7]) <= 0) {
      p = 0;
    } else if (((uint16_t) i[7]) > 0) {
    p = N19daa2019(i);
    } 
    return p;
  }

uint16_t N108e43517(uint16_t i[]) {
    uint16_t p ;
    if (i[2] == NULL) {
      p = 0;
    } else if (((uint16_t) i[2]) <= 1548) {
    p = Nbe834a18(i);
    } else if (((uint16_t) i[2]) > 1548) {
      p = 0;
    } 
    return p;
  }

uint16_t N1eec5fe16(uint16_t i[]) {
    uint16_t p ;
    if (i[5] == NULL) {
      p = 1;
    } else if (((uint16_t) i[5]) <= 133) {
      p = 1;
    } else if (((uint16_t) i[5]) > 133) {
    p = N108e43517(i);
    } 
    return p;
  }

uint16_t N227bd015(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 0;
    } else if (((uint16_t) i[0]) <= 2424) {
    p = N1eec5fe16(i);
    } else if (((uint16_t) i[0]) > 2424) {
      p = 1;
    } 
    return p;
  }

uint16_t N89a2d914(uint16_t i[]) {
    uint16_t p ;
    if (i[7] == NULL) {
      p = 0;
    } else if (((uint16_t) i[7]) <= 2) {
    p = N227bd015(i);
    } else if (((uint16_t) i[7]) > 2) {
      p = 1;
    } 
    return p;
  }

uint16_t N35135a13(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 4;
    } else if (((uint16_t) i[0]) <= 3036) {
      p = 4;
    } else if (((uint16_t) i[0]) > 3036) {
      p = 7;
    } 
    return p;
  }

uint16_t N54f74212(uint16_t i[]) {
    uint16_t p ;
    if (i[3] == NULL) {
      p = 7;
    } else if (((uint16_t) i[3]) <= 68) {
    p = N35135a13(i);
    } else if (((uint16_t) i[3]) > 68) {
    p = N89a2d914(i);
    } 
    return p;
  }

uint16_t N154b57411(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 1;
    } else if (((uint16_t) i[0]) <= 2657) {
      p = 1;
    } else if (((uint16_t) i[0]) > 2657) {
      p = 7;
    } 
    return p;
  }

uint16_t N10e98d810(uint16_t i[]) {
    uint16_t p ;
    if (i[5] == NULL) {
      p = 7;
    } else if (((uint16_t) i[5]) <= 7) {
      p = 7;
    } else if (((uint16_t) i[5]) > 7) {
      p = 1;
    } 
    return p;
  }

uint16_t Ne596c99(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 7;
    } else if (((uint16_t) i[1]) <= 1998) {
    p = N10e98d810(i);
    } else if (((uint16_t) i[1]) > 1998) {
      p = 7;
    } 
    return p;
  }

uint16_t Nea9cf18(uint16_t i[]) {
    uint16_t p ;
    if (i[7] == NULL) {
      p = 4;
    } else if (((uint16_t) i[7]) <= 0) {
      p = 4;
    } else if (((uint16_t) i[7]) > 0) {
    p = Ne596c99(i);
    } 
    return p;
  }

uint16_t N2eb6e97(uint16_t i[]) {
    uint16_t p ;
    if (i[5] == NULL) {
      p = 7;
    } else if (((uint16_t) i[5]) <= 22) {
    p = Nea9cf18(i);
    } else if (((uint16_t) i[5]) > 22) {
    p = N154b57411(i);
    } 
    return p;
  }

uint16_t N13829886(uint16_t i[]) {
    uint16_t p ;
    if (i[6] == NULL) {
      p = 1;
    } else if (((uint16_t) i[6]) <= 29) {
    p = N2eb6e97(i);
    } else if (((uint16_t) i[6]) > 29) {
    p = N54f74212(i);
    } 
    return p;
  }

uint16_t N1a66ce85(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 7;
    } else if (((uint16_t) i[4]) <= 21) {
      p = 7;
    } else if (((uint16_t) i[4]) > 21) {
      p = 2;
    } 
    return p;
  }

uint16_t N1e6e48b4(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 2;
    } else if (((uint16_t) i[1]) <= 1867) {
    p = N1a66ce85(i);
    } else if (((uint16_t) i[1]) > 1867) {
    p = N13829886(i);
    } 
    return p;
  }

uint16_t N17e7f883(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 0;
    } else if (((uint16_t) i[4]) <= 482) {
    p = N1e6e48b4(i);
    } else if (((uint16_t) i[4]) > 482) {
    p = Nc386d20(i);
    } 
    return p;
  }

uint16_t Nd16dc82(uint16_t i[]) {
    uint16_t p ;
    if (i[7] == NULL) {
      p = 3;
    } else if (((uint16_t) i[7]) <= 13) {
      p = 3;
    } else if (((uint16_t) i[7]) > 13) {
      p = 6;
    } 
    return p;
  }

uint16_t N91a0c31(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 3;
    } else if (((uint16_t) i[1]) <= 2405) {
    p = Nd16dc82(i);
    } else if (((uint16_t) i[1]) > 2405) {
      p = 5;
    } 
    return p;
  }

uint16_t N4c4a0d0(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 3;
    } else if (((uint16_t) i[0]) <= 2033) {
    p = N91a0c31(i);
    } else if (((uint16_t) i[0]) > 2033) {
    p = N17e7f883(i);
    } 
    return p;
  }

 uint16_t classify_c45(uint16_t i[])
 {

    uint16_t p ;
    p = N4c4a0d0(i);
    return p;
  }
 
/*
//konferenzraum felix
  uint16_t classify_c45(uint16_t i[])
     {

    uint16_t p ;
    p = N167e0030(i);
    return p;
  }
   uint16_t N167e0030(uint16_t i[]) {
    uint16_t p ;
    if (i[6] == NULL) {
      p = 0;
    } else if (((uint16_t) i[6]) <= 680) {
    p = Na407871(i);
    } else if (((uint16_t) i[6]) > 680) {
    p = N5e43ee5(i);
    } 
    return p;
  }
   uint16_t Na407871(uint16_t i[]) {
    uint16_t p ;
    if (i[6] == NULL) {
      p = 1;
    } else if (((uint16_t) i[6]) <= 74) {
    p = Nea5d872(i);
    } else if (((uint16_t) i[6]) > 74) {
    p = N944d4a4(i);
    } 
    return p;
  }
   uint16_t Nea5d872(uint16_t i[]) {
    uint16_t p ;
    if (i[7] == NULL) {
      p = 7;
    } else if (((uint16_t) i[7]) <= 1) {
    p = Na288153(i);
    } else if (((uint16_t) i[7]) > 1) {
      p = 1;
    } 
    return p;
  }
   uint16_t Na288153(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 7;
    } else if (((uint16_t) i[4]) <= 94) {
      p = 7;
    } else if (((uint16_t) i[4]) > 94) {
      p = 0;
    } 
    return p;
  }
   uint16_t N944d4a4(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 2;
    } else if (((uint16_t) i[1]) <= 1986) {
      p = 2;
    } else if (((uint16_t) i[1]) > 1986) {
      p = 0;
    } 
    return p;
  }
   uint16_t N5e43ee5(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 3;
    } else if (((uint16_t) i[0]) <= 2006) {
    p = Nbde56d6(i);
    } else if (((uint16_t) i[0]) > 2006) {
    p = N121784f7(i);
    } 
    return p;
  }
   uint16_t Nbde56d6(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 3;
    } else if (((uint16_t) i[1]) <= 2385) {
      p = 3;
    } else if (((uint16_t) i[1]) > 2385) {
      p = 5;
    } 
    return p;
  }
   uint16_t N121784f7(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 6;
    } else if (((uint16_t) i[0]) <= 2780) {
      p = 6;
    } else if (((uint16_t) i[0]) > 2780) {
      p = 4;
    } 
    return p;
  }

*/

/*
// g66

uint16_t classify_c45(uint16_t i[])
{
    uint16_t p ;
    p = N94d3130(i);
    return p;
}
uint16_t N94d3130(uint16_t i[]) {
    uint16_t p ;
    if (i[5] == NULL) {
      p = 10;
    } else if (((uint16_t) i[5]) <= 2943) {
    p = Nad9f5d1(i);
    } else if (((uint16_t) i[5]) > 2943) {
    p = N83df1421(i);
    } 
    return p;
}
uint16_t Nad9f5d1(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 10;
    } else if (((uint16_t) i[4]) <= 32) {
      p = 10;
    } else if (((uint16_t) i[4]) > 32) {
    p = Nb99e4c2(i);
    } 
    return p;
}
uint16_t Nb99e4c2(uint16_t i[]) {
    uint16_t p ;
    if (i[2] == NULL) {
      p = 10;
    } else if (((uint16_t) i[2]) <= 1642) {
    p = N47c1303(i);
    } else if (((uint16_t) i[2]) > 1642) {
    p = N1e06b1217(i);
    } 
    return p;
}
uint16_t N47c1303(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 10;
    } else if (((uint16_t) i[1]) <= 2372) {
    p = Ndc54344(i);
    } else if (((uint16_t) i[1]) > 2372) {
    p = N1664f1a12(i);
    } 
    return p;
}
uint16_t Ndc54344(uint16_t i[]) {
    uint16_t p ;
    if (i[2] == NULL) {
      p = 4;
    } else if (((uint16_t) i[2]) <= 1557) {
    p = N11c41235(i);
    } else if (((uint16_t) i[2]) > 1557) {
      p = 10;
    } 
    return p;
}
uint16_t N11c41235(uint16_t i[]) {
    uint16_t p ;
    if (i[2] == NULL) {
      p = 4;
    } else if (((uint16_t) i[2]) <= 1548) {
    p = N1f873dd6(i);
    } else if (((uint16_t) i[2]) > 1548) {
    p = N749ebc9(i);
    } 
    return p;
}
uint16_t N1f873dd6(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 6;
    } else if (((uint16_t) i[0]) <= 2328) {
    p = N7ee46a7(i);
    } else if (((uint16_t) i[0]) > 2328) {
    p = Nc62c078(i);
    } 
    return p;
}
uint16_t N7ee46a7(uint16_t i[]) {
    uint16_t p ;
    if (i[2] == NULL) {
      p = 4;
    } else if (((uint16_t) i[2]) <= 1546) {
      p = 4;
    } else if (((uint16_t) i[2]) > 1546) {
      p = 6;
    } 
    return p;
}
uint16_t Nc62c078(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 4;
    } else if (((uint16_t) i[0]) <= 2385) {
      p = 4;
    } else if (((uint16_t) i[0]) > 2385) {
      p = 10;
    } 
    return p;
}
uint16_t N749ebc9(uint16_t i[]) {
    uint16_t p ;
    if (i[7] == NULL) {
      p = 6;
    } else if (((uint16_t) i[7]) <= 1) {
    p = N61856510(i);
    } else if (((uint16_t) i[7]) > 1) {
    p = N7cdc5811(i);
    } 
    return p;
}
uint16_t N61856510(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 10;
    } else if (((uint16_t) i[0]) <= 2246) {
      p = 10;
    } else if (((uint16_t) i[0]) > 2246) {
      p = 6;
    } 
    return p;
}
uint16_t N7cdc5811(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 10;
    } else if (((uint16_t) i[1]) <= 2250) {
      p = 10;
    } else if (((uint16_t) i[1]) > 2250) {
      p = 4;
    } 
    return p;
}
uint16_t N1664f1a12(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 5;
    } else if (((uint16_t) i[0]) <= 2421) {
    p = N1d33eef13(i);
    } else if (((uint16_t) i[0]) > 2421) {
    p = N1b0d2d016(i);
    } 
    return p;
}
uint16_t N1d33eef13(uint16_t i[]) {
    uint16_t p ;
    if (i[3] == NULL) {
      p = 7;
    } else if (((uint16_t) i[3]) <= 70) {
    p = N1c8f64414(i);
    } else if (((uint16_t) i[3]) > 70) {
    p = N9ff58815(i);
    } 
    return p;
}
uint16_t N1c8f64414(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 10;
    } else if (((uint16_t) i[4]) <= 63) {
      p = 10;
    } else if (((uint16_t) i[4]) > 63) {
      p = 7;
    } 
    return p;
}
uint16_t N9ff58815(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 6;
    } else if (((uint16_t) i[0]) <= 2323) {
      p = 6;
    } else if (((uint16_t) i[0]) > 2323) {
      p = 5;
    } 
    return p;
}
uint16_t N1b0d2d016(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 7;
    } else if (((uint16_t) i[1]) <= 2534) {
      p = 7;
    } else if (((uint16_t) i[1]) > 2534) {
      p = 5;
    } 
    return p;
}
uint16_t N1e06b1217(uint16_t i[]) {
    uint16_t p ;
    if (i[3] == NULL) {
      p = 8;
    } else if (((uint16_t) i[3]) <= 131) {
    p = N9576fd18(i);
    } else if (((uint16_t) i[3]) > 131) {
    p = N1136da620(i);
    } 
    return p;
}
uint16_t N9576fd18(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 8;
    } else if (((uint16_t) i[0]) <= 2422) {
    p = Nb6e38519(i);
    } else if (((uint16_t) i[0]) > 2422) {
      p = 10;
    } 
    return p;
}
uint16_t Nb6e38519(uint16_t i[]) {
    uint16_t p ;
    if (i[7] == NULL) {
      p = 10;
    } else if (((uint16_t) i[7]) <= 0) {
      p = 10;
    } else if (((uint16_t) i[7]) > 0) {
      p = 8;
    } 
    return p;
}
uint16_t N1136da620(uint16_t i[]) {
    uint16_t p ;
    if (i[2] == NULL) {
      p = 9;
    } else if (((uint16_t) i[2]) <= 1850) {
      p = 9;
    } else if (((uint16_t) i[2]) > 1850) {
      p = 10;
    } 
    return p;
}
uint16_t N83df1421(uint16_t i[]) {
    uint16_t p ;
    if (i[3] == NULL) {
      p = 2;
    } else if (((uint16_t) i[3]) <= 78) {
    p = N1aabc2922(i);
    } else if (((uint16_t) i[3]) > 78) {
    p = N2758d023(i);
    } 
    return p;
}
uint16_t N1aabc2922(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 2;
    } else if (((uint16_t) i[0]) <= 2119) {
      p = 2;
    } else if (((uint16_t) i[0]) > 2119) {
      p = 0;
    } 
    return p;
}
uint16_t N2758d023(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 3;
    } else if (((uint16_t) i[0]) <= 2399) {
      p = 3;
    } else if (((uint16_t) i[0]) > 2399) {
      p = 1;
    } 
    return p;
}*/

/*
//konferenzraum
uint16_t classify_c45(uint16_t i[]){
    uint16_t p ;
    p = N507aaf65(i);
    return p;
}
uint16_t N507aaf65(uint16_t i[]) {
    uint16_t p ;
    if (i[6] == NULL) {
      p = 0;
    } else if (((uint16_t) i[6]) <= 680) {
    p = N1a685ae66(i);
    } else if (((uint16_t) i[6]) > 680) {
    p = N126267170(i);
    } 
    return p;
}
uint16_t N1a685ae66(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 7;
    } else if (((uint16_t) i[4]) <= 31) {
      p = 7;
    } else if (((uint16_t) i[4]) > 31) {
    p = N19297ab67(i);
    } 
    return p;
}
uint16_t N19297ab67(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 2;
    } else if (((uint16_t) i[1]) <= 2136) {
    p = N1238fa568(i);
    } else if (((uint16_t) i[1]) > 2136) {
    p = N1abd8cb69(i);
    } 
    return p;
}
uint16_t N1238fa568(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 2;
    } else if (((uint16_t) i[1]) <= 1975) {
      p = 2;
    } else if (((uint16_t) i[1]) > 1975) {
      p = 3;
    } 
    return p;
}
uint16_t N1abd8cb69(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 0;
    } else if (((uint16_t) i[1]) <= 2282) {
      p = 0;
    } else if (((uint16_t) i[1]) > 2282) {
      p = 1;
    } 
    return p;
}
uint16_t N126267170(uint16_t i[]) {
    uint16_t p ;
    if (i[0] == NULL) {
      p = 3;
    } else if (((uint16_t) i[0]) <= 2033) {
    p = N1a5fdb971(i);
    } else if (((uint16_t) i[0]) > 2033) {
    p = Nb4962672(i);
    } 
    return p;
}
uint16_t N1a5fdb971(uint16_t i[]) {
    uint16_t p ;
    if (i[1] == NULL) {
      p = 3;
    } else if (((uint16_t) i[1]) <= 2367) {
      p = 3;
    } else if (((uint16_t) i[1]) > 2367) {
      p = 5;
    } 
    return p;
}
uint16_t Nb4962672(uint16_t i[]) {
    uint16_t p ;
    if (i[4] == NULL) {
      p = 4;
    } else if (((uint16_t) i[4]) <= 4343) {
      p = 4;
    } else if (((uint16_t) i[4]) > 4343) {
      p = 6;
    } 
    return p;
}*/



