#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'SerialMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 104

# The Active Message type associated with this message.
AM_TYPE = 66

class SerialMsg(tinyos.message.Message.Message):
    # Create a new SerialMsg of size 104.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=104):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <SerialMsg> \n"
        try:
            s += "  [length=0x%x]\n" % (self.get_length())
        except:
            pass
        try:
            s += "  [address=0x%x]\n" % (self.get_address())
        except:
            pass
        try:
            s += "  [rssi=0x%x]\n" % (self.get_rssi())
        except:
            pass
        try:
            s += "  [data=";
            for i in range(0, 100):
                s += "0x%x " % (self.getElement_data(i) & 0xff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: length
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'length' is signed (False).
    #
    def isSigned_length(self):
        return False
    
    #
    # Return whether the field 'length' is an array (False).
    #
    def isArray_length(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'length'
    #
    def offset_length(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'length'
    #
    def offsetBits_length(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'length'
    #
    def get_length(self):
        return self.getUIntElement(self.offsetBits_length(), 8, 1)
    
    #
    # Set the value of the field 'length'
    #
    def set_length(self, value):
        self.setUIntElement(self.offsetBits_length(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'length'
    #
    def size_length(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'length'
    #
    def sizeBits_length(self):
        return 8
    
    #
    # Accessor methods for field: address
    #   Field type: int
    #   Offset (bits): 8
    #   Size (bits): 16
    #

    #
    # Return whether the field 'address' is signed (False).
    #
    def isSigned_address(self):
        return False
    
    #
    # Return whether the field 'address' is an array (False).
    #
    def isArray_address(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'address'
    #
    def offset_address(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'address'
    #
    def offsetBits_address(self):
        return 8
    
    #
    # Return the value (as a int) of the field 'address'
    #
    def get_address(self):
        return self.getUIntElement(self.offsetBits_address(), 16, 1)
    
    #
    # Set the value of the field 'address'
    #
    def set_address(self, value):
        self.setUIntElement(self.offsetBits_address(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'address'
    #
    def size_address(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'address'
    #
    def sizeBits_address(self):
        return 16
    
    #
    # Accessor methods for field: rssi
    #   Field type: short
    #   Offset (bits): 24
    #   Size (bits): 8
    #

    #
    # Return whether the field 'rssi' is signed (False).
    #
    def isSigned_rssi(self):
        return False
    
    #
    # Return whether the field 'rssi' is an array (False).
    #
    def isArray_rssi(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'rssi'
    #
    def offset_rssi(self):
        return (24 / 8)
    
    #
    # Return the offset (in bits) of the field 'rssi'
    #
    def offsetBits_rssi(self):
        return 24
    
    #
    # Return the value (as a short) of the field 'rssi'
    #
    def get_rssi(self):
        return self.getUIntElement(self.offsetBits_rssi(), 8, 1)
    
    #
    # Set the value of the field 'rssi'
    #
    def set_rssi(self, value):
        self.setUIntElement(self.offsetBits_rssi(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'rssi'
    #
    def size_rssi(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'rssi'
    #
    def sizeBits_rssi(self):
        return 8
    
    #
    # Accessor methods for field: data
    #   Field type: short[]
    #   Offset (bits): 32
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'data' is signed (False).
    #
    def isSigned_data(self):
        return False
    
    #
    # Return whether the field 'data' is an array (True).
    #
    def isArray_data(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'data'
    #
    def offset_data(self, index1):
        offset = 32
        if index1 < 0 or index1 >= 100:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'data'
    #
    def offsetBits_data(self, index1):
        offset = 32
        if index1 < 0 or index1 >= 100:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'data' as a short[]
    #
    def get_data(self):
        tmp = [None]*100
        for index0 in range (0, self.numElements_data(0)):
                tmp[index0] = self.getElement_data(index0)
        return tmp
    
    #
    # Set the contents of the array 'data' from the given short[]
    #
    def set_data(self, value):
        for index0 in range(0, len(value)):
            self.setElement_data(index0, value[index0])

    #
    # Return an element (as a short) of the array 'data'
    #
    def getElement_data(self, index1):
        return self.getUIntElement(self.offsetBits_data(index1), 8, 1)
    
    #
    # Set an element of the array 'data'
    #
    def setElement_data(self, index1, value):
        self.setUIntElement(self.offsetBits_data(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'data'
    #
    def totalSize_data(self):
        return (800 / 8)
    
    #
    # Return the total size, in bits, of the array 'data'
    #
    def totalSizeBits_data(self):
        return 800
    
    #
    # Return the size, in bytes, of each element of the array 'data'
    #
    def elementSize_data(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'data'
    #
    def elementSizeBits_data(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'data'
    #
    def numDimensions_data(self):
        return 1
    
    #
    # Return the number of elements in the array 'data'
    #
    def numElements_data():
        return 100
    
    #
    # Return the number of elements in the array 'data'
    # for the given dimension.
    #
    def numElements_data(self, dimension):
        array_dims = [ 100,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'data' with a String
    #
    def setString_data(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_data(i, ord(s[i]));
         self.setElement_data(l, 0) #null terminate
    
    #
    # Read the array 'data' as a String
    #
    def getString_data(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_data(i) == chr(0):
                break
            carr += self.getElement_data(i)
        return carr
    
