/*
    This file is part of Titan.

    Titan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as 
    published by the Free Software Foundation, either version 3 of 
    the License, or (at your option) any later version.

    Titan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Titan. If not, see <http://www.gnu.org/licenses/>.
*/

/*****************************************************************************
 * Semester Thesis WSPack 6 2006
 * ETH Zürich, Inst. for Electronics
 *
 * Autor:               Felix Arnold (farnold@ee.ethz.ch)
 * Target:              MSP430F1611 Processor
 * Build Environment:   IAR Embedded Workbench V3.3A/W32
 * File:                c45.c
 *
 * C45 Decision Tree 
 * (Tree and Java-Code generated by Weka, parsed and transformed to 
 * C-Code by tocpp.pl
 *****************************************************************************/


#ifndef _C45_H_
#define _C45_H_

extern  uint16_t classify_c45(uint16_t i[]);
/*
//konferezraum 4 pers
extern   uint16_t N4c4a0d0(uint16_t i[]) ;
extern   uint16_t N91a0c31(uint16_t i[]) ;
extern   uint16_t Nd16dc82(uint16_t i[]) ;
extern   uint16_t N17e7f883(uint16_t i[]) ;
extern   uint16_t N1e6e48b4(uint16_t i[]) ;
extern   uint16_t N1a66ce85(uint16_t i[]) ;
extern   uint16_t N13829886(uint16_t i[]) ;
extern   uint16_t N2eb6e97(uint16_t i[]) ;
extern   uint16_t Nea9cf18(uint16_t i[]) ;
extern   uint16_t Ne596c99(uint16_t i[]) ;
extern   uint16_t N10e98d810(uint16_t i[]) ;
extern   uint16_t N154b57411(uint16_t i[]) ;
extern   uint16_t N54f74212(uint16_t i[]) ;
extern   uint16_t N35135a13(uint16_t i[]) ;
extern   uint16_t N89a2d914(uint16_t i[]) ;
extern   uint16_t N227bd015(uint16_t i[]) ;
extern   uint16_t N1eec5fe16(uint16_t i[]) ;
extern   uint16_t N108e43517(uint16_t i[]) ;
extern   uint16_t Nbe834a18(uint16_t i[]) ;
extern   uint16_t N19daa2019(uint16_t i[]) ;
extern   uint16_t Nc386d20(uint16_t i[]) ;
extern   uint16_t N4c8b8421(uint16_t i[]) ;
extern   uint16_t N15ba1ef22(uint16_t i[]) ;
*/
/*
//konferenzraum felix
extern   uint16_t N167e0030(uint16_t i[]) ;
extern   uint16_t Na407871(uint16_t i[]) ;
extern   uint16_t Nea5d872(uint16_t i[]) ;
extern   uint16_t Na288153(uint16_t i[]) ;
extern   uint16_t N944d4a4(uint16_t i[]) ;
extern   uint16_t N5e43ee5(uint16_t i[]) ;
extern   uint16_t Nbde56d6(uint16_t i[]) ;
extern   uint16_t N121784f7(uint16_t i[]) ;
*/
/*
// g66
extern   uint16_t N94d3130(uint16_t i[]) ;
extern   uint16_t Nad9f5d1(uint16_t i[]) ;
extern   uint16_t Nb99e4c2(uint16_t i[]) ;
extern   uint16_t N47c1303(uint16_t i[]) ;
extern   uint16_t Ndc54344(uint16_t i[]) ;
extern   uint16_t N11c41235(uint16_t i[]) ;
extern   uint16_t N1f873dd6(uint16_t i[]) ;
extern   uint16_t N7ee46a7(uint16_t i[]) ;
extern   uint16_t Nc62c078(uint16_t i[]) ;
extern   uint16_t N749ebc9(uint16_t i[]) ;
extern   uint16_t N61856510(uint16_t i[]) ;
extern   uint16_t N7cdc5811(uint16_t i[]) ;
extern   uint16_t N1664f1a12(uint16_t i[]) ;
extern   uint16_t N1d33eef13(uint16_t i[]) ;
extern   uint16_t N1c8f64414(uint16_t i[]) ;
extern   uint16_t N9ff58815(uint16_t i[]) ;
extern   uint16_t N1b0d2d016(uint16_t i[]) ;
extern   uint16_t N1e06b1217(uint16_t i[]) ;
extern   uint16_t N9576fd18(uint16_t i[]) ;
extern   uint16_t Nb6e38519(uint16_t i[]) ;
extern   uint16_t N1136da620(uint16_t i[]) ;
extern   uint16_t N83df1421(uint16_t i[]) ;
extern   uint16_t N1aabc2922(uint16_t i[]) ;
extern   uint16_t N2758d023(uint16_t i[]) ;
*/

// konferenzraum
extern   uint16_t N507aaf65(uint16_t i[]) ;
extern   uint16_t N1a685ae66(uint16_t i[]) ;
extern   uint16_t N19297ab67(uint16_t i[]) ;
extern   uint16_t N1238fa568(uint16_t i[]) ;
extern   uint16_t N1abd8cb69(uint16_t i[]) ;
extern   uint16_t N126267170(uint16_t i[]) ;
extern   uint16_t N1a5fdb971(uint16_t i[]) ;
extern   uint16_t Nb4962672(uint16_t i[]) ;




#endif //_C45_H_
